// TODO: ultimately generated by openapi-typescript from /openapi.json of the backend
// (`npx openapi-typescript http://localhost:8000/openapi.json -o src/types/api.ts`)
// — see docs/technical/frontend.md section 8.
// For now written by hand, in line with docs/technical/database-schema.md.
// SSE events (ChatStreamEvent) are a deliberate exception — OpenAPI does not describe them,
// they will be defined manually in the final version too.

export type PersonaType =
  | "personal_trainer"
  | "dietitian"
  | "sport_psychologist"
  | "psychologist"
  | "motor_coach"
  | "badminton_coach"
  | "custom";

export type DetailLevel = "simple" | "detailed";

export type ModerationStatus = "pending" | "approved" | "rejected";

export interface TemplateOverrides {
  columns: string[];
}

export interface Persona {
  id: string;
  user_id: string;
  type: PersonaType;
  name: string;
  system_prompt: string;
  base_template_id: string | null;
  plan_template_id: string | null;
  template_overrides: TemplateOverrides | null;
  detail_level: DetailLevel;
  custom_result_category: string | null;
  // ADR-13: stable identifier for "/slug message" in the general chat —
  // generated from type+name, regenerated on name change, unique per user.
  slug: string;
  is_shared: boolean;
  moderation_status: ModerationStatus;
  cloned_from_persona_id: string | null;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface PersonaTemplate {
  id: string;
  type: PersonaType;
  default_prompt: string;
  label: string;
  created_at: string;
}

export interface PlanTemplate {
  id: string;
  name: string;
  suggested_for: string[];
  default_columns: string[];
  default_rows: (string | number)[][] | null;
  created_at: string;
}

export interface PersonaCreateInput {
  base_template_id: string;
  type: PersonaType;
  name: string;
  system_prompt: string;
  detail_level: DetailLevel;
  plan_template_id?: string | null;
  template_overrides?: TemplateOverrides | null;
  custom_result_category?: string | null;
}

// The limit of active personas is PER ACCOUNT (profiles.max_active_personas, ADR-12) —
// the personas list response carries it directly, so the UI never hardcodes "5".
export interface PersonasListResponse {
  items: Persona[];
  max_active_personas: number;
}

export type PersonaUpdateInput = Partial<
  Pick<
    Persona,
    | "name"
    | "system_prompt"
    | "detail_level"
    | "template_overrides"
    | "custom_result_category"
    | "active"
    | "plan_template_id"
  >
>;

export type ChatRole = "user" | "assistant" | "tool";

// ADR-13: 'persona' session (1:1, persona_id NOT NULL) vs 'general' (auto-routing,
// persona_id NULL) — see docs/technical/architecture.md section 3a.
export type ChatSessionType = "persona" | "general";

export interface ChatSession {
  id: string;
  user_id: string;
  persona_id: string | null;
  session_type: ChatSessionType;
  title: string | null;
  turn_in_progress?: boolean;
  created_at: string;
  updated_at: string;
}

// ADR-13: attribution per message — in a 'general' session different assistant/tool
// messages may come from different personas.
export type InvokedVia = "auto_routed" | "slash_command" | "multi_slash" | null;

/** A single Goat consultation (`consult_persona`) — preview of the trainer's question and answer. */
export interface ConsultDetail {
  /** `tool_call_id` of the call — dedup live vs history. */
  toolCallId: string;
  personaLabel: string;
  question: string;
  answer: string;
}

export interface ChatMessage {
  id: string;
  session_id: string;
  role: ChatRole;
  content: string;
  tool_calls: unknown | null;
  persona_id: string | null;
  invoked_via: InvokedVia;
  created_at: string;
  /** Consultations assigned to this Goat message (history + live); FE-only, not from the API. */
  consultDetails?: ConsultDetail[];
}

export type ResultCategory =
  | "strength"
  | "diet"
  | "swimming"
  | "triathlon"
  | "badminton"
  | "custom";

export interface Result {
  id: string;
  user_id: string;
  category: ResultCategory;
  metric: string;
  value: number;
  unit: string;
  logged_date: string;
  source: "agent" | "manual";
  source_persona_id: string | null;
  is_custom: boolean;
  notes: string | null;
  created_at: string;
}

export type PlanPeriodType = "week" | "month";
export type PlanStatus = "generating" | "ready" | "partial_ready" | "error";

export interface Plan {
  id: string;
  user_id: string;
  period_type: PlanPeriodType;
  start_date: string;
  end_date: string;
  status: PlanStatus;
  created_at: string;
  updated_at: string;
}

import type { PlanItemRow } from "@/lib/plan-item-content";

export interface PlanItemContent {
  title: string;
  columns: string[];
  /** Positional arrays OR `{ [column]: value }` objects from the backend. */
  rows: PlanItemRow[];
  notes: string | null;
}

export interface PlanItem {
  id: string;
  plan_id: string;
  item_date: string;
  item_type: string;
  persona_id: string;
  content: PlanItemContent;
  schema_version: number;
  created_at: string;
}

export type PlanGenerationJobStatus =
  | "pending"
  | "running"
  | "success"
  | "partial_success"
  | "error";

export type PlanGenerationPersonaStatus = "pending" | "running" | "done" | "failed";

export interface PlanGenerationJobPersonaBreakdown {
  persona_id: string;
  status: PlanGenerationPersonaStatus;
  retry_count: number;
  last_error: string | null;
}

export interface PlanRangeResponse {
  plan: Plan | null;
  items: PlanItem[];
}

export interface GeneratePlanInput {
  period_type: PlanPeriodType;
  start_date: string;
}

export interface GeneratePlanResponse {
  plan_id: string;
  /** Backend returns `id`; alias `job_id` available in the OpenAPI response. */
  id: string;
  job_id?: string;
}

export interface PlanGenerationJob {
  id: string;
  plan_id: string;
  status: PlanGenerationJobStatus;
  error_message: string | null;
  attempts: number;
  created_at: string;
  started_at: string | null;
  finished_at: string | null;
  /** Backend: `personas`; alias `breakdown` kept for compatibility in the store. */
  personas?: PlanGenerationJobPersonaBreakdown[];
  breakdown?: PlanGenerationJobPersonaBreakdown[];
}

export type PlanGenerationPhase = "preparing" | "coordinating" | "generating_personas" | "harmonizing" | "finished";

export interface PlanGenerationProgressEvent extends PlanGenerationJob {
  phase: PlanGenerationPhase;
}

// ADR-16: the limit is an explicit budget in USD per account (profiles.usage_budget_usd),
// NOT a subscription plan — the `tier` column was removed from usage_limits.
// `usage_budget_usd` physically lives in `profiles` (persistent independently of the period),
// but the endpoint that returns current usage (`GET /api/v1/usage`) conveniently returns
// both together, so the frontend can compute the proactive "90% of budget" badge
// (frontend.md section 10) without an extra request.
export interface UsageLimits {
  user_id: string;
  period_start: string;
  period_renews_at: string;
  messages_used: number;
  tokens_used: number;
  plan_generations_used: number;
  cost_usd_used: number;
  usage_budget_usd: number;
}

// Biometric profile — SHARED across all of the user's personas (distinguish from
// the system `personas.persona_constraints`, hidden from the end-user API).
// Ultimately filled conversationally (tool `update_user_profile` in any conversation)
// — this type describes both the shape returned by `GET /profile` and the body of
// `PATCH /profile` (form-fallback). See docs/technical/ai-pipeline.md section 0, ADR-11.
export type Sex = "male" | "female" | "other";
export type ActivityLevel = "sedentary" | "light" | "moderate" | "active" | "very_active";
export type PrimaryGoal =
  | "lose_weight"
  | "build_muscle"
  | "improve_endurance"
  | "general_health"
  | "sport_specific";

export interface UserProfile {
  user_id: string;
  height_cm: number | null;
  weight_kg: number | null;
  date_of_birth: string | null;
  sex: Sex | null;
  activity_level: ActivityLevel | null;
  primary_goal: PrimaryGoal | null;
  notes: string | null;
  updated_at: string;
}

export type UserProfileUpdate = Partial<Omit<UserProfile, "user_id" | "updated_at">>;

// Admin view of a user's account — the limit of active personas is PER ACCOUNT, editable by
// the admin (not a global constant, ADR-12); the amount is in USD (not a Free/Pro plan, ADR-16).
export interface AdminDeployInfo {
  component: "api";
  app_version: string;
  environment: string;
  git_sha: string | null;
  git_sha_full: string | null;
  git_branch: string | null;
  build_time: string | null;
  git_repo: string;
}

export interface AdminUser {
  id: string;
  email?: string | null;
  nick?: string | null;
  is_admin: boolean;
  is_approved: boolean;
  max_active_personas: number;
  active_personas_count: number;
  cost_usd_used: number;
  usage_budget_usd: number;
  created_at: string;
}

export type AdminAuditAction =
  | "reset_password"
  | "edit_limits"
  | "edit_persona_limit"
  | "edit_usage_budget"
  | "edit_approval";

export interface AdminAuditLogEntry {
  id: string;
  admin_user_id: string | null;
  action: AdminAuditAction;
  target_user_id: string;
  details: Record<string, unknown> | null;
  created_at: string;
}

export type ModerationTriggerType =
  | "persona_create"
  | "persona_edit"
  | "persona_share"
  | "chat_heuristic"
  | "chat_classifier";

export type ModerationVerdict = "clean" | "injection_attempt" | "redefine_role" | "off_topic";

export interface ModerationEvent {
  id: string;
  user_id: string;
  persona_id: string | null;
  session_id: string | null;
  message_id: string | null;
  trigger_type: ModerationTriggerType;
  raw_snippet: string;
  classifier_verdict: ModerationVerdict;
  reviewed: boolean;
  created_at: string;
}

// ADR-15: account — nick + theme. Theme is NOT here (localStorage-only, useThemeStore) —
// this type describes exclusively the GET/PATCH /api/v1/account contract.
export interface Account {
  id: string;
  nick: string | null;
  is_admin: boolean;
  is_approved: boolean;
  email?: string;
}

export type AccountUpdateInput = Partial<Pick<Account, "nick">>;

export interface PrivacyConsent {
  health_data: {
    active: boolean;
    required_version: string;
    version?: string;
    granted_at?: string;
  };
  ai_disclosure: {
    acknowledged: boolean;
    required_version: string;
    version?: string;
    granted_at?: string;
  };
  withdrawn_at?: string | null;
}

// ADR-14: exercise catalog, static reference content seeded by a migration.
export type ExerciseLevel = "beginner" | "intermediate" | "advanced";

export interface Exercise {
  id: string;
  slug: string;
  name: string;
  name_en?: string | null;
  persona_type: PersonaType;
  level: ExerciseLevel;
  categories: string[];
  short_description: string;
  detail_full: string;
  common_mistakes: string | null;
  photo_path: string | null;
  /** Second frame from free-exercise-db (`…/1.jpg`); null for manual entries. */
  photo_path_2?: string | null;
}

export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
  };
}
